workflows:
  conrumbo_android:
    name: conrumbo Android
    instance_type: mac_mini_m2
    max_build_duration: 30

    environment:
      flutter: stable

    scripts:
      - name: Preparar proyecto Flutter
        script: |
          unzip -o conrumbo_mvp_v11_perfil_contacto.zip -d /tmp/conrumbo
          cd /tmp/conrumbo/conrumbo_mvp_v5_free
          flutter create . --platforms android
          flutter pub get

      - name: Generar APK
        script: |
          cd /tmp/conrumbo/conrumbo_mvp_v5_free
          flutter build apk --release

    artifacts:
      - /tmp/conrumbo/conrumbo_mvp_v5_free/build/app/outputs/flutter-apk/app-release.apk
